name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Ruby and install gems
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7'
          bundler-cache: true

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install -e services
          pip list

      - name: Cache Thrift
        id: cache-thrift
        uses: actions/cache@v2
        with:
          path: ~/install/bin
          key: ${{ runner.os }}-thrift-0.13.0-new

      - name: Make Thrift Compiler
        if: steps.cache-thrift.outputs.cache-hit != 'true'
        run: |
          export THRIFT_VERSION=0.13.0
          export buildDeps="automake bison curl flex g++ libboost-dev libboost-filesystem-dev libboost-program-options-dev libboost-system-dev libboost-test-dev  libevent-dev libssl-dev libtool make pkg-config"
          sudo apt-get install -y --no-install-recommends $buildDeps && sudo rm -rf /var/lib/apt/lists/*
          curl -sSL "http://apache.mirrors.spacedump.net/thrift/$THRIFT_VERSION/thrift-$THRIFT_VERSION.tar.gz" -o thrift.tar.gz
          mkdir -p ${HOME}/thrift
          mkdir -p ${HOME}/install
          tar zxf thrift.tar.gz -C ${HOME}/thrift --strip-components=1
          pushd ${HOME}/thrift
          ./configure --prefix=${HOME}/install --without-c_glib --without-csharp --without-python --without-netstd --without-erlang --without-rs --without-swift --without-dotnetcore --without-cpp --without-ruby --without-nodejs --without-py3 --without-go --without-php --without-java
          make
          make install
          popd
          ls -al ${HOME}/install/*

      - name: Check Thrift install
        run: |
          echo $PWD
          ls -al ${HOME}/
          ls -al ${HOME}/install/*
          echo "${HOME}/install/bin" >> $GITHUB_PATH

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 12.18.3
      - name: Find yarn cache location
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: JS package cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install packages
        run: |
          yarn install --pure-lockfile

      - name: Configure rails app
        run: |
          cp config/configuration.yml.example config/configuration.yml
          cp config/database.yml.example config/database.yml
          mkdir -p upload/store
          RAILS_ENV=test bundle exec rake db:schema:load
          bundle exec rake db:test:prepare
          RAILS_ENV=test bundle exec rake webpacker:compile

      - name: Run tests
        run: |
          echo $PATH
          WHATSOPT_COVERALLS=1 bundle exec rails test

      - name: Coveralls 
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: "./coverage/lcov.info"
 
